spring:
  application:
    name: landing-microservice
  profiles:
    active:
      - dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  sleuth:
    enabled: true
    sampler:
      probability: 100
    sender.type: web
  zipkin:
    enabled: true
    base-url: http://localhost:9411
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers:
        - localhost:29092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:29092

server:
  port: 6070
  servlet:
    context-path: /${spring.application.name}

custom:
  eureka-server-port: 6060
  eureka-context-path: /discovery-server
  eureka-server-address: localhost

eureka:
  client:
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${custom.eureka-server-address}:${custom.eureka-server-port}${custom.eureka-context-path}/eureka

#Exposing all actuator endpoints, without security
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

#Logbook Configuration
logbook:
  exclude:
    - /actuator/**
  filter.enabled: true
  secure-filter.enabled: true
  format.style: json
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  write:
    chunk-size: 50000